services:
  postgres:
    image: bitnami/postgresql:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=literalura
    volumes:
      - literalura_pg_data:/bitnami/postgresql
volumes:
  literalura_pg_data:
